services:
  # A Docker web service
  - type: web
    name: GenAI
    runtime: python
    plan: free
    autoDeploy: True
    buildCommand: pip install -r requirements.txt
    startCommand: gradio main.py